-- 30+ servicos digitais que a loja oferece. Inspirado no concierge SevenLicite.
-- Categorias: certidao_federal, certidao_trab, certidao_justica, certidao_estadual,
-- certidao_municipal, junta_comercial, documentos, certidao_socio, cert_digital,
-- consultas, credito, clube.

INSERT INTO sevenconstruction.servicos_catalogo
  (codigo, nome, categoria, modo, emissor, link_emissor,
   preco_custo, preco_venda_sugerido, comissao_loja_pct,
   descricao, pitch_curto, para_quem, casos_uso, prazo_entrega, como_vender, ordem)
VALUES

-- ========== CERTIDÕES FEDERAIS ==========
('CND_FED', 'CND Federal (Receita+PGFN)', 'certidao_federal', 'automatica',
 'Receita Federal', 'https://servicos.receitafederal.gov.br/servico/certidoes/#/home/cnpj',
 0, 25, 100,
 'Certidão Negativa de Débitos Federais e Dívida Ativa da União.',
 'Comprova que a empresa não tem dívida com a Receita Federal nem PGFN.',
 'Construtores e prestadores que vão fechar contrato grande, financiamento ou licitação pública.',
 ARRAY['Habilitação em licitação pública','Contrato com órgão público','Financiamento bancário','Cadastro de fornecedor em grande empresa','Mudança societária em junta'],
 'Na hora (até 5 minutos)',
 '"Você tá em dia com a Receita pra esse contrato? Por R$ 25 a gente tira na hora — você ganha R$ 25 e o cliente sai com a certidão pronta."',
 100),

('CND_INSS', 'Certidão INSS (negativa de débitos previdenciários)', 'certidao_federal', 'concierge',
 'Receita Federal', NULL,
 5, 35, 80,
 'Negativa de contribuição previdenciária. Hoje vem junto com CND Federal mas órgãos antigos ainda pedem separado.',
 'Comprova que a empresa não tem dívida com INSS — algumas prefeituras ainda exigem separado da CND.',
 'Construtor licitando obra pública municipal antiga.',
 ARRAY['Licitação municipal que pede certidão separada','Cadastro de prefeitura interior'],
 '1 dia útil (manual quando o automático não cobre)',
 '"Esse edital pede INSS separado da CND? A gente resolve em 1 dia útil."',
 110),

('CARTAO_CNPJ', 'Cartão CNPJ atualizado', 'certidao_federal', 'automatica',
 'Receita Federal', 'https://servicos.receita.fazenda.gov.br/Servicos/cnpjreva/Cnpjreva_Solicitacao.asp',
 0, 8, 100,
 'Cartão CNPJ atualizado direto no site da Receita.',
 'Comprovante de inscrição CNPJ atualizado — pedido em quase todo cadastro novo.',
 'Cliente que vai abrir conta empresarial, contratar serviço B2B, ou licitar.',
 ARRAY['Abertura de conta PJ em banco','Cadastro de fornecedor','Contratos com fornecedores grandes','Renovação de alvará'],
 'Na hora',
 '"Cartão CNPJ atualizado pra sua reunião com o banco — R$ 8."',
 120),

('ENQUAD_ME', 'Comprovante Enquadramento ME/EPP/Simples', 'certidao_federal', 'automatica',
 'Receita Federal', 'https://www8.receita.fazenda.gov.br/SimplesNacional/Aplicacoes/ATSPO/ConsultaOptantes.app/ConsultarOpcao.aspx',
 0, 10, 100,
 'Comprova que a empresa está enquadrada como ME/EPP ou optante do Simples Nacional.',
 'Documento essencial pra licitações com tratamento diferenciado pra ME/EPP (LC 123).',
 'Microempresa licitando — tem benefícios garantidos.',
 ARRAY['Licitação com cota MEI/ME/EPP','Comprovação de enquadramento Simples','Anexo em editais'],
 'Na hora',
 '"Você é ME/EPP? Em licitação você tem preferência de até 10%! Por R$ 10 tiramos o comprovante."',
 130),

-- ========== TRABALHISTA / FGTS ==========
('CRF_FGTS', 'CRF FGTS (Caixa)', 'certidao_trab', 'automatica',
 'Caixa Econômica Federal', 'https://consulta-crf.caixa.gov.br/consultacrf/pages/consultaEmpregador.jsf',
 0, 15, 100,
 'Certidão de Regularidade do FGTS (CRF) emitida pela Caixa.',
 'Pré-requisito de TODA licitação pública. Mostra que a empresa está em dia com o FGTS dos funcionários.',
 'Toda empresa com CLT que vai participar de licitação ou contratar grande.',
 ARRAY['Habilitação em licitação','Renovação de contrato com órgão público','Análise de fornecedor B2B','Auditoria interna'],
 'Na hora',
 '"Sua CRF tá vencida? R$ 15 pra emitir agora e ser válida por 30 dias."',
 200),

('CNDT', 'CNDT (Trabalhista)', 'certidao_trab', 'automatica',
 'TST', 'https://www.tst.jus.br/certidao',
 0, 15, 100,
 'Certidão Negativa de Débitos Trabalhistas. Emitida pelo TST.',
 'Comprova que a empresa não tem dívida trabalhista (reclamatórias com sentença, multa do MTE).',
 'Toda empresa com CLT participando de licitação.',
 ARRAY['Envelope de habilitação licitatória','Contratação por terceirizada','Análise de risco trabalhista','Aceite de proposta de cliente grande'],
 'Na hora',
 '"Tem dúvida se sua empresa tem reclamatória pendente? R$ 15 e em 5 minutos a gente checa e tira limpa."',
 210),

-- ========== COMPRAS GOVERNO ==========
('SICAF', 'SICAF — Cadastro de Fornecedor Governo Federal', 'certidao_federal', 'concierge',
 'Compras.gov.br', 'https://www.gov.br/compras/pt-br/sistemas/sicaf-digital',
 30, 150, 60,
 'Cadastro completo + atualização anual no SICAF (sistema unificado de fornecedores do governo federal).',
 'Sem SICAF, empresa não vende nada pro governo federal. É o passaporte pro mercado público.',
 'Empresa que quer vender pro governo (qualquer órgão federal).',
 ARRAY['Primeiro acesso a Compras.gov.br','Renovação anual obrigatória','Atualização de quadro societário','Inclusão de novas linhas de fornecimento'],
 '2 a 5 dias úteis (depende de validação)',
 '"Você quer vender pro governo? Sem SICAF, não dá. Por R$ 150 a gente cadastra ou renova."',
 220),

-- ========== JUSTIÇA ==========
('JUST_FED', 'Certidão Justiça Federal (Cível e Criminal)', 'certidao_justica', 'automatica',
 'Justiça Federal', 'https://www.cjf.jus.br/cjf/atendimento-ao-cidadao/certidoes',
 0, 20, 100,
 'Certidão da Justiça Federal — cobre processos cíveis e criminais em âmbito federal.',
 'Mostra se a empresa ou sócio responde a algum processo na Justiça Federal.',
 'Habilitação licitatória + due diligence M&A.',
 ARRAY['Pré-requisito de licitação federal','Análise de fornecedor de grande contrato','Verificação de sócio antes de M&A'],
 'Na hora',
 '"Quer comprovar que a empresa não tem processo federal? R$ 20 e a gente emite."',
 300),

('JUST_EST_CIVEL', 'Certidão Justiça Estadual (Cível)', 'certidao_justica', 'concierge',
 'TJ da UF', NULL,
 8, 35, 75,
 'Certidão de processos cíveis no TJ do estado.',
 'Cada UF tem seu sistema. Gera comissão maior porque exige acesso aos sistemas estaduais.',
 'Habilitação em licitação estadual + análise de risco de fornecedor B2B.',
 ARRAY['Licitação estadual','Cadastro de fornecedor em órgão estadual','Análise pré-contrato com cliente grande'],
 '1 a 3 dias úteis',
 '"A certidão estadual é mais chata — cada TJ tem um portal diferente. R$ 35 e a gente resolve."',
 310),

('JUST_EST_CRIM', 'Certidão Justiça Estadual (Criminal)', 'certidao_justica', 'concierge',
 'TJ da UF', NULL,
 8, 35, 75,
 'Certidão de processos criminais no TJ do estado.',
 'Empresas geralmente não respondem na criminal, mas alguns editais exigem.',
 'Quando o edital exige certidão criminal estadual.',
 ARRAY['Editais que exigem criminal estadual','Concurso público de órgão municipal'],
 '1 a 3 dias úteis',
 '"Edital pede criminal estadual? R$ 35 e tira hoje."',
 320),

('JUST_ELEIT', 'Certidão de Quitação Eleitoral (sócios)', 'certidao_socio', 'automatica',
 'TSE', 'https://www.tse.jus.br/eleitor/certidoes/certidao-de-quitacao-eleitoral',
 0, 12, 100,
 'Comprovante de quitação eleitoral dos sócios — alguns editais exigem.',
 'Comprova que os sócios votaram nas últimas eleições — exigência de algumas licitações públicas.',
 'Sócios da empresa licitante.',
 ARRAY['Edital de prefeitura municipal','Cadastro em conselho profissional','Concurso público'],
 'Na hora',
 '"Os sócios votaram nas últimas eleições? Tira a certidão por R$ 12 cada."',
 330),

-- ========== CARTÓRIO ==========
('NEG_FAL', 'Certidão Negativa Falência/Recuperação Judicial', 'certidao_justica', 'concierge',
 'Cartório Distribuidor', NULL,
 12, 45, 75,
 'Certidão do cartório distribuidor da comarca onde a empresa está sediada.',
 'Comprova que a empresa NÃO está em falência ou recuperação judicial. Pré-requisito de quase toda licitação.',
 'Empresa licitando + análise de crédito B2B.',
 ARRAY['Envelope licitatório','Antes de aprovar prazo > R$ 50k','Due diligence pré-fechamento','Análise pré-FIDC'],
 '1 a 2 dias úteis',
 '"Vai dar prazo grande pra esse cliente novo? R$ 45 pra dormir tranquilo sabendo que ele não está em recuperação."',
 400),

-- ========== ESTADUAIS ==========
('CND_EST', 'CND Estadual (Tributos)', 'certidao_estadual', 'concierge',
 'Sefaz da UF', NULL,
 8, 30, 80,
 'Certidão estadual da Sefaz da UF do CNPJ — não há sistema unificado.',
 'Certificado pela Sefaz do estado, comprovando regularidade do ICMS.',
 'Toda empresa que recolhe ICMS e quer licitar estadual ou vender pra órgão estadual.',
 ARRAY['Habilitação licitatória estadual','Cadastro fornecedor Sefaz/SES','Renovação de IE'],
 '1 dia útil',
 '"Combo Federal+Estadual? Por R$ 50 economiza o trabalho de fazer separado."',
 500),

('IE_ATIVA', 'Comprovante Inscrição Estadual ativa', 'certidao_estadual', 'automatica',
 'Sefaz da UF', NULL,
 0, 12, 100,
 'Print do sistema da Sefaz mostrando que a IE está ativa.',
 'Documento simples que muitos clientes pedem antes de fechar contrato.',
 'Cliente B2B pedindo comprovação de regularidade.',
 ARRAY['Cadastro inicial em distribuidor','Comprovação a fornecedor B2B','Certificação para emissão NFe'],
 'Na hora',
 '"Cliente novo pediu comprovante de IE? Em 5 minutos a gente envia em PDF."',
 510),

-- ========== MUNICIPAIS ==========
('CND_MUN', 'CND Municipal (Tributos)', 'certidao_municipal', 'concierge',
 'Prefeitura', NULL,
 8, 28, 80,
 'Certidão emitida pela prefeitura, atestando regularidade de IPTU, ISS e outros tributos municipais.',
 'Empresa em dia com prefeitura — pré-requisito de quase toda licitação municipal.',
 'Toda empresa licitando município + clientes que vão renovar alvará.',
 ARRAY['Habilitação em licitação municipal','Renovação de alvará comercial','Cadastro em órgão municipal'],
 '1 a 2 dias úteis',
 '"Vai licitar na prefeitura? Sem CND municipal não passa."',
 600),

('ALVARA', 'Alvará de Funcionamento', 'certidao_municipal', 'concierge',
 'Prefeitura', NULL,
 30, 120, 60,
 'Renovação ou primeira via do alvará municipal — varia bastante por cidade.',
 'Documento obrigatório pra abrir/manter qualquer estabelecimento comercial. Renovação anual.',
 'Toda loja, escritório, prestador com endereço comercial.',
 ARRAY['Renovação anual do alvará','Mudança de endereço comercial','Abertura de filial','Mudança de atividade (CNAE)'],
 '5 a 30 dias úteis (varia por cidade)',
 '"Seu alvará venceu? A gente assume tudo (vistoria + bombeiros + sanitária) por R$ 120 + taxas da prefeitura."',
 610),

('ISS_DIA', 'Comprovante ISS em dia', 'certidao_municipal', 'automatica',
 'Prefeitura', NULL,
 0, 15, 100,
 'Print do sistema municipal mostrando ISS em dia.',
 'Documento simples — algumas prefeituras pedem em cadastros.',
 'Empresa de serviços (qualquer prestador municipal).',
 ARRAY['Renovação de cadastro de prestador','Concurso de prefeitura'],
 'Na hora',
 '"Vai renovar cadastro na prefeitura? R$ 15 e a gente comprova."',
 620),

-- ========== JUNTA COMERCIAL ==========
('JC_SIMPLES', 'Certidão Simplificada — Junta Comercial', 'junta_comercial', 'concierge',
 'Junta Comercial', NULL,
 15, 50, 70,
 'Certidão Simplificada da Junta Comercial: dados básicos + sócios atuais + capital social.',
 'Resumo oficial da empresa direto da Junta. Substitui contrato social em muitos casos.',
 'Análise de M&A + due diligence + abertura de conta PJ.',
 ARRAY['Banco pediu para abrir conta','Análise pré-investimento','Atualização cadastral em órgão público','Comprovação societária ao cliente'],
 '1 a 3 dias úteis',
 '"Cliente pediu certidão da Junta? R$ 50 e em 2 dias entregamos."',
 700),

('JC_INTEIRO', 'Certidão Inteiro Teor — Junta Comercial', 'junta_comercial', 'concierge',
 'Junta Comercial', NULL,
 30, 120, 60,
 'Histórico COMPLETO da empresa: todas as alterações contratuais já registradas.',
 'Documento mais completo da Junta — usado em M&A, processos judiciais, due diligence séria.',
 'Investidor analisando empresa + advogado em processo + grande contrato.',
 ARRAY['Due diligence M&A','Processo judicial societário','Análise de investimento','Apresentação ao banco para crédito >500k'],
 '3 a 7 dias úteis',
 '"Análise pesada do cliente? Inteiro Teor mostra TUDO desde a fundação. R$ 120."',
 710),

-- ========== DOCUMENTOS DA EMPRESA ==========
('CONTR_SOC', 'Contrato Social atualizado (cópia autenticada)', 'documentos', 'concierge',
 'Cartório', NULL,
 25, 80, 65,
 'Cópia autenticada do contrato social mais recente.',
 'Pedido em quase todo cadastro de fornecedor grande, banco e órgão público.',
 'Toda empresa licitando, abrindo conta, ou sendo cadastrada como fornecedor.',
 ARRAY['Abertura de conta PJ','Cadastro fornecedor de grande empresa','Habilitação licitatória','Renovação de alvará'],
 '1 a 3 dias úteis',
 '"Cliente pediu Contrato Social autenticado? R$ 80 e a gente entrega."',
 800),

('BAL_PAT', 'Balanço Patrimonial (com contador)', 'documentos', 'concierge',
 'Contador', NULL,
 100, 350, 50,
 'Balanço Patrimonial assinado pelo contador, comprovando situação financeira.',
 'Exigido em licitações de obra pública (edital pede índices: liquidez corrente, geral, etc).',
 'Construtor licitando obra pública + crédito empresarial alto.',
 ARRAY['Licitação de obra pública (lei 14.133)','Habilitação econômico-financeira','Análise de crédito >R$ 100k','Concorrência em concurso de prefeitura'],
 '5 a 10 dias úteis',
 '"Edital pede balanço com índices? R$ 350 e o contador parceiro entrega — você ganha R$ 175."',
 810),

('DRE', 'DRE — Demonstração de Resultado do Exercício', 'documentos', 'concierge',
 'Contador', NULL,
 80, 250, 50,
 'DRE assinada pelo contador, mostrando faturamento e lucro.',
 'Complemento ao Balanço, usado em editais e crédito.',
 'Mesmas situações do Balanço.',
 ARRAY['Habilitação licitatória','Análise de crédito','Justificativa de capital social','Apresentação a investidor'],
 '5 a 10 dias úteis',
 '"DRE pra licitação ou banco? Combo com balanço por R$ 500."',
 820),

('ATEST_CAP', 'Atestado de Capacidade Técnica', 'documentos', 'concierge',
 'Cliente anterior', NULL,
 50, 200, 50,
 'Atestado emitido por cliente anterior comprovando que a empresa executou serviço similar.',
 'Pré-requisito técnico da maioria dos editais de obra. A loja pode auxiliar a obter de cliente.',
 'Construtor que já executou obra e quer comprovar capacidade.',
 ARRAY['Habilitação técnica em licitação de obra','Comprovação para concorrência grande','Cadastro de fornecedor especializado'],
 '7 a 30 dias (depende cliente)',
 '"Precisa de atestado de obra anterior? Ajudamos a redigir e correr atrás do cliente que assina."',
 830),

-- ========== PESSOAIS DOS SÓCIOS ==========
('ANT_PF', 'Antecedentes Criminais (Polícia Federal)', 'certidao_socio', 'automatica',
 'Polícia Federal', 'https://servicos.dpf.gov.br/antecedentes-criminais/certidao',
 0, 18, 100,
 'Antecedentes federais de cada sócio.',
 'Pré-requisito de licitação pública e de algumas profissões reguladas (segurança privada, transporte).',
 'Sócios + funcionários em cargo de confiança.',
 ARRAY['Habilitação licitatória federal','Concurso de empresa de segurança','Renovação de carteira de motorista profissional','Concurso público'],
 'Na hora (online)',
 '"R$ 18 por sócio e tira na hora. Combo de 2 sócios por R$ 30."',
 900),

('ANT_EST', 'Antecedentes Criminais Estadual', 'certidao_socio', 'concierge',
 'Polícia Civil', NULL,
 5, 25, 80,
 'Antecedentes da Polícia Civil do estado.',
 'Algumas atividades reguladas (vigilância, transporte) exigem antecedentes da PC além da PF.',
 'Sócios em atividades específicas.',
 ARRAY['Cadastro em órgão estadual','Concurso de empresa de transporte','Licença para porte de arma'],
 '1 a 3 dias úteis',
 '"Atividade especial precisa antecedentes da PC? R$ 25 e a gente emite."',
 910),

('CPF_REG', 'CPF Regular dos sócios', 'certidao_socio', 'automatica',
 'Receita Federal', 'https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublica.asp',
 0, 8, 100,
 'Comprovante de CPF regular para cada sócio.',
 'Verificação básica antes de qualquer movimento societário ou cadastro.',
 'Cadastro em conta bancária + cadastro de fornecedor + dúvida sobre CPF do sócio.',
 ARRAY['Abertura de conta PJ pediu','Cadastro em órgão público','Verificar CPF de novo sócio antes de incluir'],
 'Na hora',
 '"R$ 8 por sócio. Bom check antes de fechar contrato."',
 920),

-- ========== CERTIFICADO DIGITAL ==========
('CERT_DIG_A1', 'Certificado Digital A1 e-CNPJ (1 ano)', 'cert_digital', 'paga',
 'Autoridade Certificadora', NULL,
 90, 200, 50,
 'Certificado A1 emitido por AC parceira (Serasa, Soluti, etc) — fica salvo no computador.',
 'Substitui A3 (token físico). Necessário pra emissão de NFe, e-Social, Sped, RAIS.',
 'Toda empresa que emite NFe ou opera no eSocial.',
 ARRAY['Empresa migrando do A3 pro A1','Primeira emissão NFe','Conexão eSocial doméstico ou empresarial','Acesso ao Portal CTF da Receita'],
 '1 dia útil (validação por foto + selfie)',
 '"Token A3 perdido ou vencido? A1 fica direto no PC, R$ 200 por 1 ano vs R$ 380 do A3."',
 1000),

('CERT_DIG_A3', 'Certificado Digital A3 e-CNPJ (3 anos)', 'cert_digital', 'paga',
 'Autoridade Certificadora', NULL,
 250, 450, 45,
 'Certificado A3 em token USB ou cartão (físico).',
 'Mais seguro que A1 (não copia), 3 anos de validade.',
 'Empresa que prefere segurança física + escritório com mais de 1 usuário.',
 ARRAY['Substituir A3 vencido','Compra inicial A3','Empresa que tem múltiplos contadores'],
 '3 a 5 dias úteis (envio do token)',
 '"Quer mais segurança e validade longa? A3 por R$ 450, dura 3 anos."',
 1010),

-- ========== CONSULTAS ==========
('CONS_CNPJ', 'Consulta CNPJ Completa', 'consultas', 'automatica',
 'SevenConstruction', NULL,
 0, 15, 100,
 'Tudo sobre um CNPJ: dados RFB + sócios + cruzamento + compliance (CADIN/PGFN).',
 'Análise rápida pra qualificar cliente, validar fornecedor, due diligence simples.',
 'Vendedor avaliando lead + análise de crédito + investigação básica.',
 ARRAY['Antes de aprovar prazo grande','Validação de novo fornecedor','Mapeamento de grupo econômico','Investigação de calote prévio'],
 'Na hora (sistema próprio)',
 '"R$ 15 e você sabe TUDO sobre o CNPJ. Investe R$ 15 antes de fechar R$ 5.000 a prazo?"',
 1100),

('CONS_SCORE', 'Score de Crédito Empresa (Serasa)', 'consultas', 'paga',
 'Serasa Experian', NULL,
 12, 45, 60,
 'Rating Serasa Empresa + análise composta com capital + tempo de mercado.',
 'Score de 0-1000 que mede saúde financeira da empresa pra decidir prazo/limite.',
 'Toda venda a prazo + crédito + análise de fornecedor.',
 ARRAY['Política de crédito (>700 libera 90d, <500 só à vista)','Análise pré-FIDC','Renovação de limite com cliente','Decisão de aceitar pedido grande'],
 'Na hora (API Serasa)',
 '"Antes de aprovar prazo: R$ 45 pra ver score real. >700 = libera. <500 = só à vista. Vira política."',
 1110),

('CONS_PROT', 'Consulta de Protesto', 'consultas', 'paga',
 'IEPTB / Cenprot', NULL,
 8, 35, 75,
 'Lista todos os protestos em nome da empresa em todos os cartórios do Brasil.',
 'Mostra dívidas concretas que a empresa tem em cartório.',
 'Análise de risco antes de fechar prazo + monitoramento de cliente.',
 ARRAY['Antes de aceitar boleto a prazo','Análise pré-FIDC','Cliente atrasou pagamento — checar histórico'],
 'Na hora',
 '"Cliente atrasando? Por R$ 35 vê se tem outros protestos. Decisão informada."',
 1120),

-- ========== CRÉDITO ==========
('SIM_FIDC', 'Simulação de proposta FIDC/Antecipação', 'credito', 'automatica',
 'SevenConstruction (mock)', NULL,
 0, 20, 100,
 'Simulação de antecipação de recebível com taxa estimada baseada em RFB+compliance.',
 'Cliente quer parcelar a compra? Faz simulação na hora e mostra o custo.',
 'Loja vendendo material a prazo grande + cliente querendo entender custo da antecipação.',
 ARRAY['Cliente pediu pra parcelar','Simulação de boleto a prazo','Justificativa de juros pro cliente'],
 'Na hora',
 '"Cliente quer parcelar em 3x sem juros? R$ 20 e mostramos o custo real."',
 1200),

-- ========== CLUBE ==========
('CLUBE', 'Clube de Vantagens (mensal)', 'clube', 'paga',
 'White label (Allya/Lecupon)', NULL,
 25, 49, 50,
 'Acesso a 3000+ empresas com desconto: farmácia, cinema, restaurante, posto, passagem aérea.',
 'Substitui desconto direto no produto. Cliente paga R$ 49/mês e economiza muito mais com parceiros.',
 'Cliente recorrente + funcionários da empresa-cliente + qualquer adulto.',
 ARRAY['Em vez de 5% de desconto, oferece o Clube','Programa de fidelidade da loja','Benefício a funcionários da empresa-cliente','Recurrência: R$ 49 × N clientes = recorrência'],
 'Acesso na hora (login + senha por email)',
 '"Você daria 5% de desconto? São R$ 50 numa NF de R$ 1k. Em vez disso, o Clube por R$ 49/mês — cliente economiza muito mais E você fatura R$ 24 todo mês."',
 1300)

ON CONFLICT (codigo) DO UPDATE SET
  nome = EXCLUDED.nome,
  categoria = EXCLUDED.categoria,
  modo = EXCLUDED.modo,
  emissor = EXCLUDED.emissor,
  link_emissor = EXCLUDED.link_emissor,
  preco_custo = EXCLUDED.preco_custo,
  preco_venda_sugerido = EXCLUDED.preco_venda_sugerido,
  comissao_loja_pct = EXCLUDED.comissao_loja_pct,
  descricao = EXCLUDED.descricao,
  pitch_curto = EXCLUDED.pitch_curto,
  para_quem = EXCLUDED.para_quem,
  casos_uso = EXCLUDED.casos_uso,
  prazo_entrega = EXCLUDED.prazo_entrega,
  como_vender = EXCLUDED.como_vender,
  ordem = EXCLUDED.ordem;
